### ISSUE TITLE
JSON Error in Moodle 3.5

### ISSUE THREAD

**Issue by mrvinceo** [lucisgit/moodle-assignfeedback_structured#2]
Hi Tony,

The latest release seems to have caused some trouble on our Moodle 3.5 install; wherever we add structured Criteria to an assignment (or where it already existed), we're now getting an error when attempting to grade: 

> SyntaxError Unexpected token < in JSON at position 0

For newly created assignments, the Grader is available, but as soon as some Structured Criteria is set for the assignment, the error appears. The console log is below:

```
17XHR finished loading: POST "<URL>".
DevTools failed to parse SourceMap: https://learn.oca.ac.uk/lib/requirejs.php/-1/core/popper.js.map
jquery-3.2.1.min.js:2 jQuery.Deferred exception: Unexpected token < in JSON at position 0 SyntaxError: Unexpected token < in JSON at position 0
    at parse (<anonymous>)
    at Qb (https://learn.oca.ac.uk/lib/javascript.php/-1/lib/jquery/jquery-3.2.1.min.js:4:10192)
    at A (https://learn.oca.ac.uk/lib/javascript.php/-1/lib/jquery/jquery-3.2.1.min.js:4:13719)
    at XMLHttpRequest.<anonymous> (https://learn.oca.ac.uk/lib/javascript.php/-1/lib/jquery/jquery-3.2.1.min.js:4:16323) undefined
r.Deferred.exceptionHook @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
fire @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
f.<computed> @ jquery-3.2.1.min.js:2
requestFail @ first.js:316

```
(etc. etc.)

We're about to upgrade to Moodle 3.6, so if this error is limited to 3.5, we'll just proceed with the upgrade.

Many thanks,
Paul

**Comment by tonyjbutler** [comment]
Thanks for letting me know Paul. I'll look into this as soon as I can.

**Comment by mrvinceo** [comment]
Many thanks Tony; great plugin by the way!

**Comment by tonyjbutler** [comment]
Thanks Paul, but I've been unable to reproduce this. Could you describe the exact steps necessary to trigger the error please?

**Comment by mrvinceo** [comment]
Apologies Tony; I've just been through the process again on a fresh install and no errors appeared. Although it seems to be the Feedback plugin that triggers the issue in our production environment (when text is entered into any of the criteria fields, the JSON error appears on the Grading layout), it seems to be actually caused by an Atto plugin - specifically Echo360, which we're trialling. Removing Echo360 from the toolbar seems to resolve the issue. Many thanks for your prompt responses and sorry again for jumping the gun!

**Comment by tonyjbutler** [comment]
No problem Paul, glad you got it sorted.
